### ISSUE TITLE
discord logic suggestion

### ISSUE THREAD

**Issue by Una-P** [Jaehyuk-Lee/FFXIV-KR-PF-Client-test#1]
> !document.querySelector("input#discord").checked||this.discord.match(this.discordServerRegex)&&this.discord.match(this.discordIDRegex)||(e+="올바른 디스코드 정보를 입력하세요. (사용자명#0000 혹은 서버 초대 주소)\<br>"),

> document.querySelector("input#discord").checked&&!this.discord.match(this.discordIDRegex)&&!this.discord.match(this.discordServerRegex)&&(e+="올바른 디스코드 정보를 입력하세요. (사용자명#0000 혹은 서버 초대 주소)\<br>"),

작업하신게 흥미로와서 조금 손대보다가 디스코드 체크가 작동하지 않는것같아 수정제안을 올립니다.
깃에선 라인구분이 안되어있어서 통째로 변경되는것같아 풀리는 넣지못했습니다.

**Comment by Jaehyuk-Lee** [comment]
음.. 어떤게 안되는건가요? `https://discord.gg/xxxxXx` 입력했을 때는 잘 되는데

**Comment by Una-P** [comment]
![image](https://user-images.githubusercontent.com/39465903/81275076-1fb50680-908c-11ea-9dbf-8ff640f05240.png)

-----------------------------------


![image](https://user-images.githubusercontent.com/39465903/81275111-2cd1f580-908c-11ea-885c-721db43e839b.png)

어... 비공개로 작업하시는거에선 고치셨을수도있겠네요ㅋㅋ
올리신 코드 직접받거나 io페이지에서는 동작이안되거든요

**Comment by Jaehyuk-Lee** [comment]
아 그렇네요. 뭘 잘못했는지 찾았어요. 감사합니다.

근데 이게 작업은 거의 안하고 있고 내년에야 제대로 테스트해볼 수 있을 정도가 될 것 같아요.

**Comment by Una-P** [comment]
좋은작품이 나왔으면좋겠어요! 수고해주셔서 감사합니다
